In [ ]:
#data preprocessing

#Handling missing values:

In [49]:
import pandas as pd
import numpy as np

In [79]:
data={ 'Patient_ID':[101,102,103,104,105],
      'Name':['Arun','Raji','Priya','Kavin','Ramya'],
       'Age':[27,35,None,54,42],
       'Gender':['Male',None,'Female','Male','Female'],
       'Disease' :['Fever','Cough',None,'Anemia','Tyroid'],
      'Stable':['Yes','No','Yes','No',None]
       }

In [80]:
import pandas as pd
df=pd.DataFrame(data)

In [52]:
df

   Patient_ID   Name   Age  Gender Disease Stable
0         101   Arun  27.0    Male   Fever    Yes
1         102   Raji  35.0    None   Cough     No
2         103  Priya   NaN  Female    None    Yes
3         104  Kavin  54.0    Male  Anemia     No
4         105  Ramya  42.0  Female  Tyroid   None

In [53]:
df.isnull()

   Patient_ID   Name    Age  Gender  Disease  Stable
0       False  False  False   False    False   False
1       False  False  False    True    False   False
2       False  False   True   False     True   False
3       False  False  False   False    False   False
4       False  False  False   False    False    True

In [54]:
df.isnull().sum()

Patient_ID    0
Name          0
Age           1
Gender        1
Disease       1
Stable        1
dtype: int64

In [55]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipython-input-694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [56]:
df

   Patient_ID   Name   Age  Gender Disease Stable
0         101   Arun  27.0    Male   Fever    Yes
1         102   Raji  35.0    None   Cough     No
2         103  Priya  39.5  Female    None    Yes
3         104  Kavin  54.0    Male  Anemia     No
4         105  Ramya  42.0  Female  Tyroid   None

In [57]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)

/tmp/ipython-input-3554240144.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)

In [59]:
df

   Patient_ID   Name   Age  Gender Disease Stable
0         101   Arun  27.0    Male   Fever    Yes
1         102   Raji  35.0  Female   Cough     No
2         103  Priya  39.5  Female    None    Yes
3         104  Kavin  54.0    Male  Anemia     No
4         105  Ramya  42.0  Female  Tyroid   None

In [61]:
df['Disease'].fillna(df['Disease'].mode()[0],inplace=True)

In [63]:
df

   Patient_ID   Name   Age  Gender Disease Stable
0         101   Arun  27.0    Male   Fever    Yes
1         102   Raji  35.0  Female   Cough     No
2         103  Priya  39.5  Female  Anemia    Yes
3         104  Kavin  54.0    Male  Anemia     No
4         105  Ramya  42.0  Female  Tyroid   None

In [65]:
df['Stable'].fillna(df['Stable'].mode()[0],inplace=True)

In [67]:
df

   Patient_ID   Name   Age  Gender Disease Stable
0         101   Arun  27.0    Male   Fever    Yes
1         102   Raji  35.0  Female   Cough     No
2         103  Priya  39.5  Female  Anemia    Yes
3         104  Kavin  54.0    Male  Anemia     No
4         105  Ramya  42.0  Female  Tyroid     No

In [68]:
#Encoding :

In [90]:
import pandas as pd
import numpy as np

In [91]:
data={ 'Patient_ID':[101,102,103,104,105],
      'Name':['Arun','Raji','Priya','Kavin','Ramya'],
       'Age':[27,35,31,54,42],
       'Gender':['Male','Female','Female','Male','Female'],
       'Disease' :['Fever','Cough','Anemia','Anemia','Tyroid'],
      'Stable':['Yes','No','Yes','No','yes']
       }

In [93]:
df=pd.DataFrame(data)

In [94]:
df

   Patient_ID   Name  Age  Gender Disease Stable
0         101   Arun   27    Male   Fever    Yes
1         102   Raji   35  Female   Cough     No
2         103  Priya   31  Female  Anemia    Yes
3         104  Kavin   54    Male  Anemia     No
4         105  Ramya   42  Female  Tyroid    yes

In [ ]:
#encoding categorical to numerical value

In [95]:
from sklearn.preprocessing import LabelEncoder

In [96]:
LE=LabelEncoder()

In [97]:
df['Name']=LE.fit_transform(df['Name'])

In [98]:
df

   Patient_ID  Name  Age  Gender Disease Stable
0         101     0   27    Male   Fever    Yes
1         102     3   35  Female   Cough     No
2         103     2   31  Female  Anemia    Yes
3         104     1   54    Male  Anemia     No
4         105     4   42  Female  Tyroid    yes

In [100]:
df['Gender']=LE.fit_transform(df['Gender'])

In [102]:
df

   Patient_ID  Name  Age  Gender Disease Stable
0         101     0   27       1   Fever    Yes
1         102     3   35       0   Cough     No
2         103     2   31       0  Anemia    Yes
3         104     1   54       1  Anemia     No
4         105     4   42       0  Tyroid    yes

In [104]:
df['Disease']=LE.fit_transform(df['Disease'])

In [105]:
df

   Patient_ID  Name  Age  Gender  Disease Stable
0         101     0   27       1        2    Yes
1         102     3   35       0        1     No
2         103     2   31       0        0    Yes
3         104     1   54       1        0     No
4         105     4   42       0        3    yes

In [107]:
df['Stable']=LE.fit_transform(df['Stable'])

In [108]:
df

   Patient_ID  Name  Age  Gender  Disease  Stable
0         101     0   27       1        2       1
1         102     3   35       0        1       0
2         103     2   31       0        0       1
3         104     1   54       1        0       0
4         105     4   42       0        3       2

In [ ]:
# Feature scaling :[normalize]

In [116]:
emp={
    'Age':[25,28,36,54],
      'salary':[15000,35000,43000,90000]
    }

In [117]:
import pandas as pd

In [118]:
df=pd.DataFrame(emp)

In [119]:
df

   Age  salary
0   25   15000
1   28   35000
2   36   43000
3   54   90000

In [122]:
from sklearn.preprocessing import MinMaxScaler

In [127]:
Scalar=MinMaxScaler()

In [128]:
norm=Scalar.fit_transform(df)

In [129]:
print(norm)

[[0.         0.        ]
 [0.10344828 0.26666667]
 [0.37931034 0.37333333]
 [1.         1.        ]]